DROP TABLE HISTORIA_TURNIEJU;
DROP TABLE UCZESTNIK_TURNIEJU;
DROP TABLE TURNIEJ;
DROP TABLE PUNKTY;
DROP TABLE ROZGRYWKA;
DROP TABLE GRA;
DROP TABLE ZNAJOMI;
DROP TABLE KONTO;
DROP TABLE KONTO_DRUZYNOWE;
DROP TABLE REGIONY;
DROP TABLE PUNKTACJA;
DROP TABLE RODZAJE;

CREATE TABLE REGIONY (
    region VARCHAR(20) PRIMARY KEY
);

CREATE TABLE RODZAJE (
    rodzaj VARCHAR(20) PRIMARY KEY
);

CREATE TABLE KONTO_DRUZYNOWE (
    id_druzyny NUMBER(6) PRIMARY KEY,
    nazwa VARCHAR(20) NOT NULL
);

CREATE TABLE KONTO (
    id NUMBER(6) PRIMARY KEY,
    region VARCHAR(20) NOT NULL REFERENCES REGIONY,
    nick VARCHAR(20) NOT NULL,
    haslo VARCHAR(20) NOT NULL,
    email VARCHAR(40) NOT NULL,
    rodzaj_konta VARCHAR(20) NOT NULL REFERENCES RODZAJE,
    id_druzyny NUMBER(6) REFERENCES KONTO_DRUZYNOWE, --nie jestem pewien ale to sie moze przydac
    nr_konta_bankowego NUMBER(20)
);

CREATE TABLE ZNAJOMI (
    gracz1 NUMBER(6) NOT NULL REFERENCES KONTO,
    gracz2 NUMBER(6) NOT NULL REFERENCES KONTO
);

CREATE TABLE GRA (
    nazwa VARCHAR(20) PRIMARY KEY,
    nazwa_rankingu VARCHAR(20) NOT NULL
);

CREATE TABLE ROZGRYWKA (
    id_rozgrywki NUMBER(8) PRIMARY KEY,
    gracz1 NUMBER(6) NOT NULL REFERENCES KONTO,
    gracz2 NUMBER(6) NOT NULL REFERENCES KONTO,
    gracz3 NUMBER(6) REFERENCES KONTO,
    gracz4 NUMBER(6) REFERENCES KONTO,
    id_zwyciezcy NUMBER(6) REFERENCES KONTO,
    gra VARCHAR(20) NOT NULL REFERENCES GRA,
    pkt_przewagi NUMBER(4),
    przebieg_partii VARCHAR(500)
);

CREATE TABLE PUNKTY (
    id_gracza NUMBER(6) REFERENCES KONTO,
    gra VARCHAR(20) REFERENCES GRA,
    liczba_punktow NUMBER(8)
);

CREATE TABLE TURNIEJ (
    id_turnieju NUMBER(8) PRIMARY KEY,
    nazwa VARCHAR(20) NOT NULL,
    gra VARCHAR(20) NOT NULL REFERENCES GRA,
    data_przeprowadzenia DATE NOT NULL
);

CREATE TABLE UCZESTNIK_TURNIEJU (
    id_gracza NUMBER(6) UNIQUE NOT NULL REFERENCES KONTO,
    id_turenieju NUMBER(8) NOT NULL REFERENCES TURNIEJ,
    punkty_turniejowe NUMBER(8) NOT NULL
);

CREATE TABLE HISTORIA_TURNIEJU (
    id_turnieju NUMBER(8) REFERENCES TURNIEJ,
    gracz1 NUMBER(6) NOT NULL REFERENCES KONTO,
    gracz2 NUMBER(6) NOT NULL REFERENCES KONTO,
    gracz3 NUMBER(6) REFERENCES KONTO,
    gracz4 NUMBER(6) REFERENCES KONTO,
    id_zwyciezcy NUMBER(6) REFERENCES KONTO,
    przebieg_partii VARCHAR(500) NOT NULL
);

CREATE TABLE PUNKTACJA (
    max NUMBER(4),
    imp NUMBER(2)
);

INSERT INTO PUNKTACJA 
    VALUES (10, 0);

INSERT INTO PUNKTACJA 
    VALUES (40, 1);

INSERT INTO PUNKTACJA 
    VALUES (80, 2);

INSERT INTO PUNKTACJA 
    VALUES (120, 3);

INSERT INTO PUNKTACJA 
    VALUES (160, 4);

INSERT INTO PUNKTACJA 
    VALUES (210, 5);

INSERT INTO PUNKTACJA 
    VALUES (260, 6);

INSERT INTO PUNKTACJA 
    VALUES (310, 7);
    
INSERT INTO PUNKTACJA 
    VALUES (360, 8);

INSERT INTO PUNKTACJA 
    VALUES (420, 9);

INSERT INTO PUNKTACJA 
    VALUES (490, 10);

INSERT INTO PUNKTACJA 
    VALUES (590, 11);

INSERT INTO PUNKTACJA 
    VALUES (740, 12);

INSERT INTO PUNKTACJA 
    VALUES (890, 13);

INSERT INTO PUNKTACJA 
    VALUES (1090, 14);

INSERT INTO PUNKTACJA 
    VALUES (1290, 15);

INSERT INTO PUNKTACJA 
    VALUES (1490, 16);

INSERT INTO PUNKTACJA 
    VALUES (1740, 17);

INSERT INTO PUNKTACJA 
    VALUES (1990, 18);

INSERT INTO PUNKTACJA 
    VALUES (2240, 19);

INSERT INTO PUNKTACJA 
    VALUES (2490, 20);  

INSERT INTO PUNKTACJA 
    VALUES (2990, 21);

INSERT INTO PUNKTACJA 
    VALUES (3490, 22);

INSERT INTO PUNKTACJA 
    VALUES (3990, 23);

INSERT INTO PUNKTACJA 
    VALUES (9999, 24);            
    
INSERT INTO REGIONY VALUES 
    ('EU');
INSERT INTO REGIONY VALUES 
    ('NA');
INSERT INTO REGIONY VALUES 
    ('ASIA');

INSERT INTO RODZAJE VALUES 
    ('Zwykle');
INSERT INTO RODZAJE VALUES 
    ('Profesjonalne');
INSERT INTO RODZAJE VALUES
    ('DRUZYNOWE')


ALTER TABLE ZNAJOMI ADD CONSTRAINT un_znaj UNIQUE (gracz1, gracz2);
ALTER TABLE PUNKTY ADD CONSTRAINT un_pkt UNIQUE (id_gracza, gra);

COMMIT;